### ISSUE TITLE
主框架、子項目採用 admin-element-vue vite 版本的可行性

### ISSUE THREAD

**Issue by penghuachen** [lqsong/admin-vue3-micro-qiankun#10]
您好，請教一個問題

目前現有幾個專案採用的是這個版本 admin-element-vue vite (https://github.com/lqsong/admin-element-vue/tree/vite.ts)

如果今天要導入 [admin-vue3-micro-qiankun](https://github.com/lqsong/admin-vue3-micro-qiankun) 這個方案的話，是不是會因為打包工具的差異(vite/webpack)，所以只能手動移植專案的程式碼到這個方案中呢？

**Comment by lqsong** [comment]
是的

**Comment by penghuachen** [comment]
了解，感謝~
