### ISSUE TITLE
error in pnpm run serve

### ISSUE THREAD

**Issue by m23100** [lqsong/admin-vue3-micro-qiankun#5]
![image](https://user-images.githubusercontent.com/1897317/175455378-30dce02e-650e-4c9a-8a1d-7cb287fd5f20.png)
重新下载项目后启动会报上面的错

**Comment by lqsong** [comment]
已修复
.browserslistrc 最后一行添加 ie 11，
是这个原因 https://github.com/vuejs/vue-cli/issues/7209#issuecomment-1164012297
