### ISSUE TITLE
页面刷新

### ISSUE THREAD

**Issue by m23100** [lqsong/admin-vue3-micro-qiankun#6]
页签切换时，希望页面不刷新，如何实现？

**Comment by lqsong** [comment]
> 页签切换时，希望页面不刷新，如何实现？

你是要记住页面填的数据不变是吧

**Comment by m23100** [comment]
> 

我把左边 头部的z-index 改成3000，比如A页面打开了弹框，再点击B页面，回来A页面，整个页面都刷新了，弹框也被关闭

**Comment by lqsong** [comment]
> 我把左边 头部的z-index 改成3000，比如A页面打开了弹框，再点击B页面，回来A页面，整个页面都刷新了，弹框也被关闭

目前这个框架没有此功能，tabNav目前只是做历史打开的记录，方便点击的作用，离开当前页就是离开了。如果你需要这样的功能，可以自己改造，利用 `keep-alive`。
