### ISSUE TITLE
外链不做跳转

### ISSUE THREAD

**Issue by m23100** [lqsong/admin-vue3-micro-qiankun#7]
菜单设置为外链时，统一新页面跳转了，如果想不跳转，程序内嵌入如何做？

**Comment by lqsong** [comment]
> 菜单设置为外链时，统一新页面跳转了，如果想不跳转，程序内嵌入如何做？

既然是外链肯定是新页面跳转啊，如果你是做内嵌，应该是做一个内部路由，路由到对应页面模板，然后在对应的页面模板做内嵌
