### ISSUE TITLE
启动项目报错，是缺少文件吗

### ISSUE THREAD

**Issue by MrBaiYinL** [lqsong/admin-vue3-micro-qiankun#8]
<img width="755" alt="image" src="https://github.com/lqsong/admin-vue3-micro-qiankun/assets/20411922/fc1a2d5a-02d1-45ed-aa4e-9fc3d56410ae">

**Comment by lqsong** [comment]
pnpm是哪个版本

**Comment by MrBaiYinL** [comment]
Version 8.5.1

**Comment by lqsong** [comment]
请查看文档pnpm要求6

**Comment by MrBaiYinL** [comment]
哈哈 是的 降到6可以了，主应用和子应用单独启动时间都还行，但是pnpm run serve启动巨慢，可以优化一下
