### ISSUE TITLE
版本太老了,很难启动

### ISSUE THREAD

**Issue by romantictravel01** [lqsong/admin-vue3-micro-qiankun#9]
1.版本太老,启动问题太多,基本启动不了
2.每个项目的name都一样启动出问题
3.如果主项目部署一台服务器,子项目部署到另外的服务器怎么处理,[umi-qiankun-micro-fe-admin](https://github.com/blueju/umi-qiankun-micro-fe-admin) 什么时间可以改成这种格式,带nginx的

**Comment by lqsong** [comment]
1、pnpm 看文档要求是6，看是否一致
2、此项目的定位就是部署到一起的DEMO，分开的话自己单独建vue项目就行
